# -*- coding: utf-8 -*-
"""Proyek Akhir.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wkspHADMktghzD4EEbalErsJPoOPkqzo

## Proyek Analisis Data: https://drive.google.com/file/d/1RaBmV6Q6FYWU4HWZs80Suqd7KQC34diQ/view?usp=sharing
- **Nama:** Muhamad Rafiudin Ruslan
- **Email:** m004b4ky2654@bangkit.academy
- **ID Dicoding:** muhamad_rafiudin

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1: Faktor apa yang paling berpengaruh terhadap jumlah pengguna sepeda?
- Pertanyaan 2: Bagaimana tren penggunaan sepeda bervariasi berdasarkan waktu?

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.cluster import KMeans
import seaborn as sns
import streamlit as st

st.title("Proyek Akhir")

"""## Data Wrangling

### Gathering Data
"""

# Load datasets
day_data = pd.read_csv('/content/day.csv')
day_data.head()

# Load datasets
hour_data = pd.read_csv('/content/hour.csv')
hour_data.head()

"""### Assessing Data"""

# Inspect data
day_data.info()
print(day_data.head())

# Inspect data
hour_data.info()
print(hour_data.head())

"""### Cleaning Data"""

# Convert 'dteday' to datetime format for easier analysis
day_data['dteday'] = pd.to_datetime(day_data['dteday'])
# Check for any anomalies or outliers in humidity and windspeed
day_data.describe()

# Convert 'dteday' to datetime format for easier analysis
hour_data['dteday'] = pd.to_datetime(hour_data['dteday'])
# Check for any anomalies or outliers in humidity and windspeed
hour_data.describe()

"""## Exploratory Data Analysis (EDA)

### Explore ...
"""

# Describe numerical features for basic statistical understanding
print(day_data[['temp', 'hum', 'windspeed', 'cnt']].describe())
print(hour_data[['temp', 'hum', 'windspeed', 'cnt']].describe())

"""## Visualization & Explanatory Analysis

### Pertanyaan 1: Faktor apa yang paling berpengaruh terhadap jumlah pengguna sepeda?
"""

# Prepare data for regression model (day.csv)
X_day = day_data[['temp', 'hum', 'windspeed']]
y_day = day_data['cnt']

# Add a constant (intercept) to the model
X_day = sm.add_constant(X_day)

# Fit the regression model
model_day = sm.OLS(y_day, X_day).fit()

# Print the summary of the regression model
print(model_day.summary())

"""### Pertanyaan 2: Bagaimana tren penggunaan sepeda bervariasi berdasarkan waktu?"""

# Group by season, month, and weekday to observe trends
season_trend = day_data.groupby('season')['cnt'].mean()
month_trend = day_data.groupby('mnth')['cnt'].mean()
weekday_trend = day_data.groupby('weekday')['cnt'].mean()

# Plot the trends
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# Season Trend
axes[0].bar(season_trend.index, season_trend.values, color='lightblue')
axes[0].set_title('Average Bike Usage by Season')
axes[0].set_xticks([1, 2, 3, 4])
axes[0].set_xticklabels(['Spring', 'Summer', 'Fall', 'Winter'])

# Month Trend
axes[1].bar(month_trend.index, month_trend.values, color='lightgreen')
axes[1].set_title('Average Bike Usage by Month')
axes[1].set_xticks(range(1, 13))
axes[1].set_xticklabels(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

# Weekday Trend
axes[2].bar(weekday_trend.index, weekday_trend.values, color='lightcoral')
axes[2].set_title('Average Bike Usage by Weekday')
axes[2].set_xticks(range(7))
axes[2].set_xticklabels(['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'])

plt.tight_layout()
plt.show()

"""**Insight:**
- Suhu (temp) memiliki pengaruh positif yang signifikan terhadap jumlah pengguna sepeda (coef: 6625.53), artinya ketika suhu meningkat, penggunaan sepeda cenderung meningkat.
- Kelembapan (hum) dan kecepatan angin (windspeed) menunjukkan pengaruh negatif yang signifikan terhadap penggunaan sepeda.
- Penggunaan Sepeda Berdasarkan Musim: Penggunaan tertinggi terjadi pada musim panas (Summer) dan terendah pada musim dingin (Winter).
- Penggunaan Sepeda Berdasarkan Bulan: Bulan Juli dan Agustus memiliki penggunaan tertinggi, sedangkan Desember dan Januari terendah.
- Penggunaan Sepeda Berdasarkan Hari: Penggunaan lebih tinggi pada akhir pekan (Sabtu khususnya) dibandingkan hari kerja.

## Analisis Lanjutan (Opsional)
"""

# Prepare additional features for regression
X_extended = day_data[['temp', 'hum', 'windspeed', 'weathersit', 'workingday', 'holiday']]
y_extended = day_data['cnt']

# Add a constant (intercept) to the model
X_extended = sm.add_constant(X_extended)

# Fit the extended regression model
model_extended = sm.OLS(y_extended, X_extended).fit()

# Print the summary of the extended regression model
print(model_extended.summary())

"""**Insight**
- Suhu (temp) masih menjadi faktor yang paling signifikan, dengan pengaruh positif terhadap jumlah pengguna sepeda.
- Kondisi cuaca (weathersit) berpengaruh negatif: saat cuaca lebih buruk (misalnya hujan atau mendung), penggunaan sepeda menurun secara signifikan.
- Hari kerja (workingday) menunjukkan korelasi positif, mengindikasikan bahwa lebih banyak pengguna sepeda pada hari kerja dibandingkan akhir pekan.
- Hari libur (holiday) memiliki dampak kecil namun negatif, menandakan bahwa penggunaan sepeda sedikit menurun pada hari libur.
"""

# Features and target
X_hour = hour_data[['temp', 'hum', 'windspeed', 'weathersit', 'hr']]
y_hour = hour_data['cnt']

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_hour, y_hour, test_size=0.3, random_state=42)

# Initialize and train the model
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

# Predict on the test set
y_pred = lin_reg.predict(X_test)

# Calculate model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

"""**Insight**
- Suhu kembali menjadi variabel yang paling kuat dalam memprediksi jumlah pengguna sepeda per jam.
- Kelembapan dan kecepatan angin berpengaruh negatif, yang berarti cuaca buruk mengurangi aktivitas bersepeda.
- Jam dalam sehari (hr) menunjukkan pola yang menarik, di mana jam-jam sibuk seperti pagi (waktu kerja) dan sore (pulang kerja) cenderung memiliki lebih - banyak pengguna sepeda.
- Evaluasi model menggunakan metrik Mean Squared Error (MSE) dan R-squared memberikan gambaran seberapa baik model ini memprediksi data.
"""

# Using casual and registered user data to create clusters
X_cluster = day_data[['casual', 'registered']]

# Create KMeans model
kmeans = KMeans(n_clusters=3, random_state=42)
day_data['cluster'] = kmeans.fit_predict(X_cluster)

# Visualizing the clusters
sns.scatterplot(x='casual', y='registered', hue='cluster', data=day_data, palette='Set1')
plt.title('K-Means Clustering of Casual and Registered Users')
plt.show()

"""**Insight**
- Hasil clustering menunjukkan bahwa ada kelompok pengguna kasual yang cenderung menggunakan sepeda lebih banyak pada akhir pekan atau hari libur, dan kelompok pengguna terdaftar yang menggunakan sepeda secara konsisten selama hari kerja.
- Salah satu klaster bisa mewakili pengguna dengan volume tinggi, yang sering menggunakan sepeda pada jam-jam sibuk selama hari kerja, seperti komuter harian.
- Klaster lainnya bisa mewakili pengguna kasual, yang lebih aktif pada hari-hari tertentu seperti akhir pekan atau pada saat cuaca lebih baik.

## Conclusion

**Faktor apa yang paling berpengaruh terhadap jumlah pengguna sepeda?**
- Kesimpulan utamanya adalah suhu memiliki pengaruh terbesar dalam meningkatkan jumlah pengguna sepeda, sementara kelembapan, kecepatan angin, dan kondisi cuaca buruk menurunkan penggunaan sepeda.

**Bagaimana tren penggunaan sepeda bervariasi berdasarkan waktu (seperti musim, bulan, hari dalam seminggu, dan jam)?**
- Kesimpulan dari pertanyaan ini adalah bahwa waktu dalam setahun dan hari dalam minggu sangat mempengaruhi jumlah pengguna sepeda. Penggunaan paling banyak terjadi pada bulan-bulan musim panas dan akhir pekan, dengan puncak penggunaan pada jam-jam sibuk di hari kerja.
"""